### ISSUE TITLE
Add support for django-entangle version 0.6

### ISSUE THREAD

**Issue by rose-pace** [django-cms/djangocms-frontend#235]
After the update of django-entangle to 0.6 I'm getting the following error while running `python3 manage.py collectstatic --noinput`:

CardLayoutForm.Meta.entangled_fields["config"] += extra_fields_row_cols.keys()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Meta' has no attribute 'entangled_fields'

The release notes for version 0.6 mention adding support for Meta.fields. I'm rolling back to the previous version of django-entangle for now. It may also be worth updating documentation to reflect the supported versions of django-entangle.

**Comment by fsbraun** [comment]
@rose-pace Thanks for reporting this. Indeed, this probably is a bug in djangocms-frontend. For now, pinning to django-entangled<0.6 will help. djangocms-frontend 2.0 will require django-entangled>=0.6. I'll update the requirements.

**Comment by pwhipp** [comment]
django-entangled<0.6 in requirements.txt is an effective workaround for me while using djangocms-frontend==1.2.1.

**Comment by fsbraun** [comment]
djangocms-frontend 2.0 will require Django-entangled 0.6
